# configure_os_redhat.yml
---
- name: Check for updates (yum)
  become: true
  yum:
    list: updates
    update_cache: true
    exclude:
      - docker*
      - kube*
  register: yum_update_ready_result
  tags:
    - package_update

# Simple output, just package name
#- name: Print packages ready for update (yum).
#- debug:
#    msg: "{{ yum_result.results | map(attribute='name') | list }}"
#    verbosity: 1

# Detailed output, package name-version-release
- name: Print packages ready for update (yum)
  debug:
    msg: "{% set output = [] %}\
        {% for result in yum_update_ready_result.results %}\
          {{ output.append( result.name ~ '-' ~ result.version ~ '-' ~ result.release ) }}\
        {% endfor %}\
      {{ output }}"
    verbosity: 1
  tags:
    - package_update

- name: Update all packages (yum)
  become: true
  yum:
    name: '*'
    state: latest
    update_cache: true
    exclude:
      - docker*
      - kube*
  register: yum_updated_result
  tags:
    - package_update

- name: Print updated packages (yum)
  debug:
    msg: "{% set output = [] %}\
        {% for result in yum_updated_result.changes.updated %}\
          {{ output.append( result[0] ) }}\
        {% endfor %}\
      {{ output }}"
    verbosity: 1
  tags:
    - package_update
  when:
    - yum_updated_result.changed == true

- name: Enable EPEL repository
  become: true
  package:
    name: epel-release
    state: latest

- name: Install python-pip
  become: true
  package:
    name: python-pip
    state: latest

- name: Install pip pexpect
  become: true
  pip:
    name: pexpect
