# configure_os.yml
---
- name: Disable SELinux
  become: true
  selinux:
    state: disabled
  register: selinux_result

- name: Restart OS when needed
  become: true
  reboot:
  when: selinux_result.reboot_required
