---
- name: Configure OS
  ansible.builtin.import_tasks: configure_os.yml

- name: Configure SELinux
  ansible.builtin.import_tasks: selinux.yml

- name: Configure firewall
  ansible.builtin.import_tasks: configure_firewalld.yml
  when: not disable_firewall

- name: Disable firewall
  ansible.builtin.import_tasks: disable_firewalld.yml
  when: disable_firewall
