# defaults.yml
---
# Docker on RedHat parameters
_docker_version: '19.03'
docker_packages:
  - 'docker-ce-{{ _docker_version }}*'
  - 'docker-ce-cli-{{ _docker_version }}*'
docker_yum_repo_url: 'https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo'
docker_yum_gpg_key: 'https://download.docker.com/linux/centos/gpg'
