# docker_prepare_redhat.yml
---
- name: Add Docker GPG key (yum)
  become: true
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: Add Docker repository (yum)
  become: true
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Add plugin for version locking (yum)
  become: true
  yum:
    name: yum-plugin-versionlock
    state: latest
