# main.yml
---
- name: Log progress
  vars:
    log_message: '[Docker Install] Starting'
  include_role:
    name: common
    tasks_from: log

# ------------------------------------------------------

- name: Prepare for Docker installation (on RedHat)
  include_tasks: docker_prepare_redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker
  import_tasks: docker_install.yml

# ------------------------------------------------------

- name: Log progress
  vars:
    log_message: '[Docker Install] Ending'
  include_role:
    name: common
    tasks_from: log
