---
- name: Install firewalld
  become: true
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start and enable firewalld service
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open ports in firewalld on Control Plane
  become: true
  ansible.posix.firewalld:
    port: '{{ item }}'
    permanent: true
    state: disabled
  loop: '{{ firewalld_control_plane_ports }}'
  when: inventory_hostname in groups['control_planes']
# check ports with command: sudo firewall-cmd --list-all

- name: Open ports in firewalld on a node
  become: true
  ansible.posix.firewalld:
    port: '{{ item }}'
    permanent: true
    state: disabled
  loop: '{{ firewalld_node_ports }}'
  when: inventory_hostname in groups['nodes']

- name: Reload firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: reloaded
