---
galaxy_info:
  role_name: ansible_user
  author: Petr Kunc
  description: Creates Ansible user account
  company: HCLSoftware
  license: Apache License 2.0
  min_ansible_version: '2.11'

dependencies: []
