---
- name: Stop and disable firewalld service
  become: true
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  register: firewalld_result
  failed_when:
    - firewalld_result.failed == true
    - '"Could not find the requested service firewalld" not in firewalld_result.msg'
