# configure_os_redhat.yml
---
- name: Get server OS hostname
  ansible.builtin.set_fact:
    os__hostname: '{{ os__hostname | default(ansible_host, true) }}'
  when: os__set_hostname or os__set_etc_hosts

- name: Set server hostname
  become: true
  ansible.builtin.hostname:
    name: '{{ os__hostname }}'
  when: os__set_hostname

- name: Insert hostname into /etc/hosts file
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ os__hostname }}'
    line: '127.0.0.1 {{ os__hostname }} {{ os__hostname.split(".")[0] }}'
    state: present
  when: os__set_etc_hosts

- name: Update all packages (yum)
  become: true
  ansible.builtin.package:
    name: '*'
    state: latest
    update_cache: true
    exclude:
      - docker*
      - kube*

- name: Install required packages
  become: true
  ansible.builtin.package:
    name: '{{ os__packages_to_install }}'
    state: present
