---
- name: Print inventory info
  ansible.builtin.debug:
    msg: |
      - All hosts the play should run:        {{ ansible_play_hosts_all | to_yaml }}
      - All hosts the play will acutally run: {{ ansible_play_batch | to_yaml }}
    verbosity: 1
  delegate_to: localhost
  run_once: true

- name: Get name of the first member in the actual control plane group
  ansible.builtin.set_fact:
    actual_cp: '{{ ansible_play_hosts_all | intersect((groups[status__control_plane_group] | default({}))) }}'

- name: Print on first node in a Control Plane group
  ansible.builtin.debug:
    msg: 'I am the first server in Control Plane group, I will perform all Kubernetes commands.'
  when:
    - actual_cp | length > 0
    - inventory_hostname == actual_cp[0]
