---
argument_specs:
  main:
    short_description: Basic Linux OS configuration
    description:
      - 'This is the main entrypoint for the role.'
      - 'It does the basic Linux configration:'
      - 'Hostname, packages update, SELinux, firewall.'
    author:
      - Petr Kunc
    options:
      os__disable_firewall:
        type: bool
        required: false
        default: false
        description:
          - 'Enable/Disable system firewall in OS.'
          - '`True` = Disable firewall.'
          - '`False` = Enable firewall and add defined rules.'
          - 'The current version of Sametime script was tested only with "true", which means firewall is disabled.'
      os__selinux:
        type: str
        required: false
        default: enforcing
        choices:
          - enforcing
          - permissive
          - disabled
        description:
          - 'Configure SELinux.'
          - 'Options: `enforcing`, `permissive`, `disabled`.'
      os__set_hostname:
        type: bool
        required: false
        default: false
        description:
          - 'Related to os__set_hostname parameter.'
          - '`True` = server hostname will be set using a hostname Linux command. '
          - '`False` = no changes will be made.'
      os__set_etc_hosts:
        type: bool
        required: false
        default: false
        description:
          - 'Related to os__set_hostname parameter.'
          - '`True` = server hostname will be stored in /etc/hosts, resolving to 192.168.0.1. '
          - '`False` = no changes will be made.'
      os__hostname:
        type: str
        required: false
        default: ''
        description:
          - 'Server hostname; if not specified, ansible_host from Ansible inventory is used.'
          - 'Related to *os__set_hostname* and *os__set_etc_hosts* parameters.'
