# check_nodes.yml
---
- name: Print node info
  vars:
    info:
      - "Inventory hostname: {{ inventory_hostname }}"
      - "CPU: {{ ansible_processor | to_yaml }}"
      - "CPU Core: {{ ansible_processor_cores }}"
      - "RAM: {{ ansible_memtotal_mb }}"
      - "OS Family: {{ ansible_os_family }}"
      - "Distribution: {{ ansible_distribution }}"
      - "Major version: {{ ansible_distribution_major_version }}"
  debug:
    msg: '{{ info | to_nice_yaml }}'

- name: Assert nodes parameters
  assert:
    that: '{{ item.test }}'
    fail_msg: 'Parameter "{{ item.arg }}" with value "{{ item.value }}" FAILED assertion tests!'
    success_msg: 'Parameter "{{ item.arg }}" with value "{{ item.value }}" passed assertion tests.'
  register: tests_nodes_results
  when: tests_nodes is defined and tests_nodes | length > 0
  loop: '{{ tests_nodes }}'
  ignore_errors: true
  no_log: '{{ not (detailed_output | default(false)) }}'

- name: Store passed results for nodes
  vars:
    new_entry:
      parameter: '{{ item.item.arg }}'
      value: '{{ item.item.value }}'
  set_fact:
    success_test_node_results: '{{ (success_test_node_results | default([])) + [ new_entry ] }}'
  loop: '{{ tests_nodes_results.results }}'
  when: not item.failed
  no_log: '{{ not (detailed_output | default(false)) }}'

- name: Store failed results for nodes
  vars:
    new_entry:
      parameter: '{{ item.item.arg }}'
      value: '{{ item.item.value }}'
  set_fact:
    fail_test_node_results: '{{ (fail_test_node_results | default([])) + [ new_entry ] }}'
  loop: '{{ tests_nodes_results.results }}'
  when: item.failed
  no_log: '{{ not (detailed_output | default(false)) }}'

- name: Print test final report for nodes
  vars:
    node: '{{ inventory_hostname }}'
    success_list: '{{ success_test_node_results | default([]) }}'
    fail_list: '{{ fail_test_node_results | default([]) }}'
  debug:
    msg: "{{ lookup('template', './test_results.j2') }}"

- name: Count number of failed tests for nodes.
  set_fact:
    fail_test_node_results_count: '{{ fail_test_node_results | default([]) | length }}'
