# server_info.yml
---
- name: Print OS info
  debug:
    msg: |
      - Inventory hostname: {{ inventory_hostname }}
      - Hostname: {{ ansible_hostname }}
      - Host: {{ ansible_host }}
      - IP addreses: {{ ansible_all_ipv4_addresses | to_yaml }}
      - OS Family: {{ ansible_os_family }}
      - Distribution: {{ ansible_distribution }}
      - Major version: {{ ansible_distribution_major_version }}
      - Release: {{ ansible_distribution_release }}
      - Distribution Version: {{ ansible_distribution_version }}
      - Kernel: {{ ansible_kernel }}
      - Architecture: {{ ansible_architecture }}
      - CPU: {{ ansible_processor | to_yaml }}
      - CPU Core: {{ ansible_processor_cores }}
      - RAM: {{ ansible_memtotal_mb }}
      - SWAP: {{ ansible_memory_mb.swap.total }}
      - Ansible user: {{ ansible_user | default(lookup('env', 'USER')) }}
      - User's home dir: {{ ansible_user_dir }}
      - Package manager: {{ ansible_pkg_mgr }}
    verbosity: 1

- name: Print on first in Masters
  debug:
    msg: 'I am the first server in Masters group, I will perform all Kubernetes commands.'
  when: inventory_hostname == groups['masters'][0]
