# setup_hosts_file.yml
---
- name: Insert servers from Ansible inventory into hosts files
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_host }}'
    state: present
  when:
    - hostvars[item].ansible_host is defined
    - hostvars[item].ansible_default_ipv4 is defined
  loop: "{{ groups['all'] }}"

- name: Add MongoDB server into hosts file
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '{{ mongo_host }}'
    line: '{{ mongo_host_ip }} {{ mongo_host }} {{ mongo_host.split(".")[0] }}'

- name: Add Sametime Proxy server into hosts file
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '{{ sametime_proxy_host }}'
    line: '{{ sametime_proxy_host_ip }} {{ sametime_proxy_host }} {{ sametime_proxy_host.split(".")[0] }}'

- name: Print hosts file
  debug:
    msg: |
      /etc/hosts file on node: {{ ansible_hostname }}
      ........................
      {{lookup("file", "/etc/hosts") }}
