---
- name: Set mydistribution variable
  ansible.builtin.set_fact:
    mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

- name: Add RPM signing key
  become: true
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
    state: present

- name: Add repository into repo.d list
  become: true
  ansible.builtin.yum_repository:
    name: docker
    description: Docker repository
    baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

- name: Install Docker
  become: true
  ansible.builtin.yum:
    name: '{{ docker__packages }}'
    state: latest
    update_cache: true

- name: Start Docker service
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Add the Ansible user to the "docker" group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true

- name: Get info on the docker host
  become: true
  community.docker.docker_host_info:
    images: true
    containers: true
    volumes: true
    networks: true
    disk_usage: true
